# Site settings
title: Kieron Tran Blog
email: kieron.qtran@gmail.com
twitter_username: kieronqtran
github_username:  kieronqtran
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#url settings
baseurl: "" 
permalink: /:title
# url: "https://kieronqtran.github.io" 
url: "https://127.0.0.1:4000" 

paginate: 2
paginate_path: "/page:num/"

# Build settings
gems: 
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - material_design_lite-sass

# static files settings
exclude: ["ssl", "Gemfile", "Gemfile.lock", "README.md"]

markdown: kramdown

sass:
  style: compressed

compress_html: # http://jch.penibelst.de/
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]


# localizations settings
languages: ["en", "vi"]

exclude_from_localizations: ["Gemfile", "scripts", "favicon.ico", "LICENSE", "README.md"]