# Site settings
title: Kieron Tran Blog
email: kieron.qtran@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://kieronqtran.github.com" # the base hostname & protocol for your site
twitter_username: kieronqtran
github_username:  kieronqtran

# Build settings
markdown: kramdown
gems: 
  # - jekyll-multiple-languages-plugin

# languages: ["en", "vi"]